import type { PostType } from '@/types/types';

export const POSTS: PostType[] = [
  {
    id: '1',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '2',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/blog-featured.jpg',
  },
  {
    id: '3',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '4',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '5',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '6',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '7',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '8',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '9',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '10',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/blog-featured.jpg',
  },
  {
    id: '11',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '12',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '13',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '14',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '15',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '16',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '17',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '18',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '19',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '20',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '21',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '22',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '23',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '24',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '25',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '26',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '27',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '28',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '29',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '30',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '31',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '32',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '33',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '34',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/blog-featured.jpg',
  },
  {
    id: '35',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '36',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '37',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '38',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '39',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
  {
    id: '40',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '41',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '42',
    urlToAvatar: '/assets/images/Floyd.jpg',
    username: 'John Doe',
    date: 'Aug 23, 2022',
    category: 'Startup',
    tags: ['Experience'],
    title: 'Step-by-step guide to choosing great font pairs',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '43',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'Sep 23, 2022',
    category: 'Startup',
    tags: ['Screen'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/design-post.jpg',
  },
  {
    id: '44',
    urlToAvatar: '/assets/images/Jonathan.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Technology'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '45',
    urlToAvatar: '/assets/images/Leslie.jpg',
    username: 'John Doe',
    date: 'Jan 23, 2022',
    category: 'Economy',
    tags: ['Marketing'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/logo-design.jpg',
  },
  {
    id: '46',
    urlToAvatar: '/assets/images/Jenny.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Life'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/figma-design.jpg',
  },
  {
    id: '47',
    urlToAvatar: '/assets/images/Dianne.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Business',
    tags: ['Business'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/build-rapport.jpg',
  },
  {
    id: '48',
    urlToAvatar: '/assets/images/.jpg',
    username: 'John Doe',
    date: 'May 23, 2022',
    category: 'Technology',
    tags: ['Experience'],
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.',
    body: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    urlToImage: '/assets/images/featured-post.jpg',
  },
];
